export const data = {
  products: [
    {
      key: "p1",
      id: "p1",
      name: "Battery Pump",
      category: "Pressure Pump",
      image: "/images/d1.jpg",
      price: 5000,
      brand: "Ralli",
      rating: 4.5,
      numreviews: 10,
      description: "Pump on Batteru",
    },
    {
      key: "p2",
      id: "p2",
      name: "Sprinkler",
      category: "Pressure Pump",
      image: "/images/d1.jpg",
      price: 5000,
      brand: "Ralli",
      rating: 4.5,
      numreviews: 10,
      description: "Paanni paanni",
    },
    {
      key: "p3",
      id: "p3",
      name: "Pesure pump",
      category: "Pressure Pump",
      image: "/images/d1.jpg",
      price: 5000,
      brand: "Ralli",
      rating: 4.5,
      numreviews: 10,
      description: "High power",
    },
    {
      key: "p4",
      id: "p4",
      name: "Motor bike",
      category: "Pressure Pump",
      image: "/images/d1.jpg",
      price: 5000,
      brand: "Ralli",
      rating: 4.5,
      numreviews: 10,
      description: "Bike hai",
    },
  ],
};
